import { Content, TDocumentDefinitions } from 'pdfmake/interfaces';
import { SaleView } from '@entity/view/sale/sale-view.entity';
import { StyleInvoice } from '@constant/style-invoice/style-invoice.constant';
import { join } from 'path';
import { Formatter } from 'src/data/helpers/formatter/formatter.helpers'; // Asegúrate de que la ruta a formatter.helpers sea correcta
const imagePath = join(__dirname, '../../../../common/assests/imagen.png');

const logo: Content = {
  image: imagePath,
  width: 120,
};

export function billReport(saleData: SaleView): TDocumentDefinitions {
  // Asegúrate de que saleDetail sea un arreglo
  const saleDetailRows = Array.isArray(saleData.saleDetail)
    ? saleData.saleDetail.map((detail) => ({
        productCode: detail.productCode,
        unitPrice: detail.unitPrice,
        quantity: detail.quantity,
        subtotal: detail.subtotal,
        taxesIdentifier: detail.taxIdentifier,
        saleDetailTotalTaxes: detail.saleDetailTotalTaxes,
        total: detail.total,
      }))
    : [];

  return {
    defaultStyle: {
      // fontSize: 8,
    },
    pageSize: 'A4',
    header: {
      text: 'Bill Report',
      alignment: 'right',
      margin: [10, 10],
    },
    footer: {
      text: 'Generated by develop Code',
      alignment: 'right',
      margin: [10, 10],
    },
    content: [
      // logo,
      {
        canvas: [
          {
            type: 'line',
            x1: 0,
            y1: 5,
            x2: 515,
            y2: 5,
            lineWidth: 1,
          },
        ],
      },

      {
        text: 'Tucan Code',
        style: 'h1',
      },

      {
        columns: [
          {
            text: [
              { text: '15 Montgomery St.\n', style: 'h3' },
              `San Francisco, CA 94104 \nBN: 123456789\n`,
              {
                link: 'https://google.com',
                text: 'https://devtalles.com',
              },
            ],
          },
          {
            text: [
              { text: 'Número de Factura: 123456\n', style: 'h3' },
              `Fecha: ${saleData.sale.saleDate}`,
            ],
            alignment: 'right',
          },
        ],
      },

      // Código QR
      {
        qr: 'https://devtalles.com',
        fit: 100,
        alignment: 'right',
      },

      // Datos del cliente
      {
        text: [
          {
            text: 'Cobrar a:\n',
            style: 'h2',
          },
          `${saleData.client.clientName}\nRazón Social: ${saleData.client.clientName}\nBN: ${saleData.client.clientIdentificacion}`,
        ],
      },

      // Tabla con los detalles de los productos
      {
        margin: [0, 20],
        layout: 'lightHorizontalLines',
        table: {
          widths: [50, '*', 'auto', 'auto', 'auto'],
          headerRows: 1,
          body: [
            [
              { text: 'ID', alignment: 'center' },
              'Producto',
              'Precio',
              'Cantidad',
              'Total',
            ],
            ...saleDetailRows.map((product) => [
              { text: product.productCode, alignment: 'center' },
              product.unitPrice,
              typeof product.quantity === 'number'
                ? Formatter.currency(product.quantity)
                : '', // Asegúrate de que product[2] sea un número
              product.subtotal,
              {
                text:
                  typeof product.saleDetailTotalTaxes === 'number'
                    ? Formatter.currency(product.saleDetailTotalTaxes)
                    : '', // Asegúrate de que product[4] sea un número
                bold: true,
                alignment: 'right',
              },
            ]),

            // Totales de la tabla
            [{}, {}, {}, {}, {}],
            [
              { text: 'Subtotal', colSpan: 4, alignment: 'right' },
              {},
              {},
              {},
              {
                text: Formatter.currency(saleData.sale.subtotal),
                bold: true,
                alignment: 'right',
              },
            ],
            [
              { text: 'Taxes', colSpan: 4, alignment: 'right' },
              {},
              {},
              {},
              {
                text: Formatter.currency(saleData.sale.saleDetailTotalTaxes),
                bold: true,
                alignment: 'right',
              },
            ],
            [
              {},
              {},
              {
                text: 'Total',
                colSpan: 2,
                alignment: 'right',
                fillColor: 'black',
                color: 'white',
                bold: true,
                margin: [5, 5],
                fontSize: 14,
              },
              {},
              {
                text: Formatter.currency(saleData.sale.totalpayable),
                bold: true,
                alignment: 'right',
                fillColor: 'black',
                color: 'white',
                margin: [5, 5],
                fontSize: 14,
              },
            ],
          ],
        },
      },
    ],

    styles: StyleInvoice,
  };
}
